// Generated by Positronic CLI
// This file provides TypeScript types for your secrets from .env

declare module '@positronic/core' {
  interface Secrets {
    NODE_ENV: string | undefined;
    R2_BUCKET_NAME: string | undefined;
    SLACK_BOT_TOKEN: string | undefined;
    GITHUB_TOKEN: string | undefined;
    DEV_SUMMARY_SLACK_CHANNEL: string | undefined;
    OPENAI_API_KEY: string | undefined;
    GOOGLE_GENERATIVE_AI_API_KEY: string | undefined;
    GMAIL_CLIENT_ID: string | undefined;
    GMAIL_CLIENT_SECRET: string | undefined;
    GMAIL_REFRESH_TOKEN_ACCOUNT1: string | undefined;
    GMAIL_REFRESH_TOKEN_ACCOUNT2: string | undefined;
    GMAIL_REFRESH_TOKEN_ACCOUNT3: string | undefined;
    NTFY_TOPIC: string | undefined;
    WORKER_URL: string | undefined;
    ROOT_PUBLIC_KEY: string | undefined;
  }
}

export {}; // Make this a module
